development:
  adapter: postgresql
  database: joyhaus_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: joyhaus_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: joyhaus_production
  pool: 5
  timeout: 5000
